function createEmptyLayoutContentBlob(layoutName, currencyId, symbol, interval, studyId) {
  const shortName = symbol.split(':')[1];
  return {
    name: layoutName,
    layout: 's',
    charts: [{
      panes: [{
        sources: [{
          type: 'MainSeries',
          id: '_seriesId',
          zorder: 0,
          haStyle: {
            studyId: 'BarSetHeikenAshi@tv-basicstudies-60',
          },
          renkoStyle: {
            studyId: 'BarSetRenko@tv-prostudies-73',
          },
          pbStyle: {
            studyId: 'BarSetPriceBreak@tv-prostudies-34',
          },
          kagiStyle: {
            studyId: 'BarSetKagi@tv-prostudies-73',
          },
          pnfStyle: {
            studyId: 'BarSetPnF@tv-prostudies-73',
          },
          rangeStyle: {
            studyId: 'BarSetRange@tv-basicstudies-72',
          },
          volFootprintStyle: {
            studyId: 'Footprint@tv-volumebyprice-104',
          },
          tpoStyle: {
            studyId: 'TPOPeriodic@tv-volumebyprice-104',
          },
          svpStyle: {
            studyId: 'VbPSessions@tv-volumebyprice-126',
          },
          formattingDeps: {
            pricescale: 10, minmov: 1, fractional: false, minmove2: 0, variable_tick_size: '',
          },
          studyBindings: {
            17: null, 18: {}, 20: null,
          },
          state: {
            style: 1,
            esdShowDividends: true,
            esdShowSplits: true,
            esdShowEarnings: true,
            esdShowBreaks: false,
            esdFlagSize: 2,
            showContinuousContractSwitches: true,
            showContinuousContractSwitchesBreaks: false,
            showFuturesContractExpiration: true,
            showLastNews: false,
            showCountdown: true,
            bidAsk: {
              visible: false,
              lineStyle: 1,
              lineWidth: 1,
              bidLineColor: '#2962FF',
              askLineColor: '#F7525F',
            },
            prePostMarket: {
              visible: true,
              lineStyle: 1,
              lineWidth: 1,
              preMarketColor: '#FB8C00',
              postMarketColor: '#2962FF',
            },
            highLowAvgPrice: {
              highLowPriceLinesVisible: false,
              highLowPriceLabelsVisible: false,
              averageClosePriceLineVisible: false,
              averageClosePriceLabelVisible: false,
              highLowPriceLinesWidth: 1,
              averagePriceLineWidth: 1,
              highLowPriceLinesColor: '',
              averagePriceLineColor: '',
            },
            visible: true,
            showPriceLine: true,
            priceLineWidth: 1,
            showPrevClosePriceLine: false,
            prevClosePriceLineWidth: 1,
            minTick: 'default',
            dividendsAdjustment: false,
            backAdjustment: false,
            settlementAsClose: true,
            sessionId: 'regular',
            sessVis: false,
            statusViewStyle: {
              fontSize: 16, showExchange: true, showInterval: true, symbolTextSource: 'description',
            },
            candleStyle: {
              drawWick: true,
              drawBorder: true,
              barColorsOnPrevClose: false,
              drawBody: true,
              borderColor: '#378658',
              upColor: '#089981',
              wickColor: '#737375',
              wickUpColor: '#089981',
              wickDownColor: '#F23645',
              downColor: '#F23645',
              borderUpColor: '#089981',
              borderDownColor: '#F23645',
            },
            volCandlesStyle: {
              drawWick: true,
              drawBorder: true,
              barColorsOnPrevClose: false,
              drawBody: true,
              borderColor: '#378658',
              upColor: '#089981',
              wickColor: '#737375',
              wickUpColor: '#089981',
              wickDownColor: '#F23645',
              downColor: '#F23645',
              borderUpColor: '#089981',
              borderDownColor: '#F23645',
            },
            hollowCandleStyle: {
              drawWick: true,
              drawBorder: true,
              drawBody: true,
              upColor: '#089981',
              downColor: '#F23645',
              borderColor: '#378658',
              borderUpColor: '#089981',
              borderDownColor: '#F23645',
              wickColor: '#737375',
              wickUpColor: '#089981',
              wickDownColor: '#F23645',
            },
            haStyle: {
              drawWick: true,
              drawBorder: true,
              showRealLastPrice: false,
              barColorsOnPrevClose: false,
              inputs: {},
              inputInfo: {},
              drawBody: true,
              borderColor: '#378658',
              upColor: '#089981',
              wickColor: '#737375',
              wickUpColor: '#089981',
              wickDownColor: '#F23645',
              downColor: '#F23645',
              borderUpColor: '#089981',
              borderDownColor: '#F23645',
            },
            barStyle: {
              barColorsOnPrevClose: false,
              dontDrawOpen: false,
              thinBars: true,
              downColor: '#F23645',
              upColor: '#089981',
            },
            hiloStyle: {
              showBorders: true,
              showLabels: true,
              drawBody: true,
              color: '#2962FF',
              borderColor: '#2962FF',
              labelColor: '#2962FF',
            },
            columnStyle: {
              barColorsOnPrevClose: true,
              priceSource: 'close',
              baselinePosition: 'bottom',
              upColor: 'rgba(8, 153, 129, 0.5)',
              downColor: 'rgba(242, 54, 69, 0.5)',
            },
            lineStyle: {
              linestyle: 0,
              linewidth: 2,
              priceSource: 'close',
              colorType: 'gradient',
              color: '#2962FF',
              gradientStartColor: '#D500F9',
              gradientEndColor: '#00BCE5',
            },
            tpoStyle: {
              linestyle: 0,
              linewidth: 2,
              priceSource: 'close',
              styles: {
                splitByBlocks: false, splitByBlocksMode: 0,
              },
              tpo: {
                showBlocks: true,
                showLetters: true,
                nonVaOpacity: 30,
                colors: {
                  gradientColors: ['#e91e63', '#00c853', '#00bcd4', '#651FFF'],
                },
              },
              levels: {
                showPOC: true,
                showPoorHigh: false,
                showPoorLow: false,
                showSingleprints: false,
                showVAH: true,
                showVAL: true,
                showMidpoint: false,
                showOpenPrice: false,
                showClosePrice: false,
                initialBalanceRange: {
                  levels: 2, visible: true,
                },
                pocColor: '#D1D4DC',
                poorHighColor: '#7C4DFF',
                poorLowColor: '#7C4DFF',
                singleprintsColor: 'rgba(224, 64, 251, 0.15)',
                vahColor: '#D1D4DC',
                valColor: '#D1D4DC',
              },
              volumeProfile: {
                visible: true,
                showValues: false,
                vah: {
                  visible: false, linestyle: 0, linewidth: 2, color: '#D1D4DC',
                },
                val: {
                  visible: false, linestyle: 0, linewidth: 2, color: '#D1D4DC',
                },
                poc: {
                  visible: false, linestyle: 0, linewidth: 2, color: '#D1D4DC',
                },
                placement: 'left_to_right',
                valuesColor: '#D1D4DC',
                volumeColor: 'rgba(38, 198, 218, 0.5)',
                valueAreaColor: 'rgba(38, 198, 218, 0.75)',
              },
              inputs: {
                periodsNum: 1,
                period: 'Day',
                blockSize: '30m',
                rowSize: 'Auto',
                ticksPerRow: 10,
                vaPercent: 70,
                extendPoorHigh: false,
                extendPoorLow: false,
                extendPOC: false,
                extendTpoVah: false,
                extendTpoVal: false,
                extendVolumePoc: false,
                extendVolumeVah: false,
                extendVolumeVal: false,
                extendSingleprints: false,
                mergePoints: '[]',
              },
              summary: {
                visible: false,
                infoBlocks: {
                  hlRange: {
                    visible: false,
                  },
                  pocPrice: {
                    visible: true,
                  },
                  rotationFactor: {
                    visible: false,
                  },
                  totalVolume: {
                    visible: false,
                  },
                  tpoCountAbovePoc: {
                    visible: false,
                  },
                  tpoCountBelowPoc: {
                    visible: false,
                  },
                  tpoCountTotal: {
                    visible: false,
                  },
                  vaRange: {
                    visible: false,
                  },
                  vahPrice: {
                    visible: true,
                  },
                  valPrice: {
                    visible: true,
                  },
                  initialBalanceHigh: {
                    visible: true,
                  },
                  initialBalanceLow: {
                    visible: true,
                  },
                  initialBalanceRange: {
                    visible: true,
                  },
                },
              },
              color: '#2962FF',
            },
            svpStyle: {
              inputs: {
                profilesSessions: 'All',
                customSession: '0930-1600',
                customSessionTZ: 'Exchange',
                volume: 'Up/Down',
                vaVolume: 70,
                extendPocRight: false,
                extendVAHRight: false,
                extendVALRight: false,
                rowsLayout: 'Number Of Rows',
                rows: 24,
              },
              volumeProfile: {
                visible: true,
                showValues: false,
                placement: 'left_to_right',
                percentWidth: 100,
                valuesColor: '#D1D4DC',
                volumeColorUp: 'rgba(38, 198, 218, 0.5)',
                volumeColorDown: 'rgba(236, 64, 122, 0.5)',
                valueAreaColorUp: 'rgba(38, 198, 218, 0.75)',
                valueAreaColorDown: 'rgba(236, 64, 122, 0.75)',
                histogramBoxColor: 'rgba(38, 198, 218, 0.05)',
              },
              vah: {
                visible: false, linestyle: 0, linewidth: 2, color: '#D1D4DC',
              },
              val: {
                visible: false, linestyle: 0, linewidth: 2, color: '#D1D4DC',
              },
              poc: {
                visible: true, linestyle: 0, linewidth: 2, color: '#D1D4DC',
              },
              developingPoc: {
                visible: false, linestyle: 0, linewidth: 1, color: '#D1D4DC',
              },
              developingVA: {
                visible: false, linestyle: 0, linewidth: 1, color: '#00bcd4',
              },
            },
            lineWithMarkersStyle: {
              linestyle: 0,
              linewidth: 2,
              priceSource: 'close',
              colorType: 'gradient',
              color: '#2962FF',
              gradientStartColor: '#D500F9',
              gradientEndColor: '#00BCE5',
            },
            steplineStyle: {
              linestyle: 0,
              linewidth: 2,
              priceSource: 'close',
              colorType: 'gradient',
              color: '#2962FF',
              gradientStartColor: '#D500F9',
              gradientEndColor: '#00BCE5',
            },
            areaStyle: {
              linestyle: 0,
              linewidth: 2,
              priceSource: 'close',
              transparency: 100,
              color1: 'rgba(41, 98, 255, 0.28)',
              color2: '#2962FF',
              linecolor: '#2962FF',
            },
            hlcAreaStyle: {
              highLineStyle: 0,
              highLineWidth: 2,
              lowLineStyle: 0,
              lowLineWidth: 2,
              closeLineStyle: 0,
              closeLineWidth: 2,
              highLineColor: '#089981',
              lowLineColor: '#F23645',
              closeLineColor: '#868993',
              highCloseFillColor: 'rgba(8, 153, 129, 0.2)',
              closeLowFillColor: 'rgba(242, 54, 69, 0.2)',
            },
            renkoStyle: {
              inputs: {
                source: 'close',
                sources: 'Close',
                boxSize: 3,
                style: 'ATR',
                atrLength: 14,
                percentageLTP: 1,
                wicks: true,
              },
              inputInfo: {
                source: {
                  name: 'Source',
                },
                sources: {
                  name: 'Source',
                },
                boxSize: {
                  name: 'Box size',
                },
                style: {
                  name: 'Style',
                },
                atrLength: {
                  name: 'ATR length',
                },
                percentageLTP: {
                  name: 'Percentage',
                },
                wicks: {
                  name: 'Wicks',
                },
              },
              upColor: '#089981',
              downColor: '#F23645',
              borderUpColor: '#089981',
              borderDownColor: '#F23645',
              upColorProjection: '#336854',
              downColorProjection: '#7f323f',
              borderUpColorProjection: '#336854',
              borderDownColorProjection: '#7f323f',
              wickUpColor: '#089981',
              wickDownColor: '#F23645',
            },
            pbStyle: {
              inputs: {
                source: 'close', lb: 3,
              },
              inputInfo: {
                source: {
                  name: 'Source',
                },
                lb: {
                  name: 'Number of line',
                },
              },
              upColor: '#089981',
              downColor: '#F23645',
              borderUpColor: '#089981',
              borderDownColor: '#F23645',
              upColorProjection: '#336854',
              downColorProjection: '#7f323f',
              borderUpColorProjection: '#336854',
              borderDownColorProjection: '#7f323f',
            },
            kagiStyle: {
              inputs: {
                source: 'close', style: 'ATR', atrLength: 14, percentageLTP: 1, reversalAmount: 1,
              },
              inputInfo: {
                source: {
                  name: 'Source',
                },
                style: {
                  name: 'Style',
                },
                atrLength: {
                  name: 'ATR length',
                },
                percentageLTP: {
                  name: 'Percentage',
                },
                reversalAmount: {
                  name: 'Reversal amount',
                },
              },
              downColor: '#F23645',
              upColor: '#089981',
              upColorProjection: '#336854',
              downColorProjection: '#7f323f',
            },
            pnfStyle: {
              inputs: {
                sources: 'Close',
                reversalAmount: 3,
                boxSize: 1,
                style: 'ATR',
                atrLength: 14,
                percentageLTP: 1,
                oneStepBackBuilding: false,
              },
              inputInfo: {
                sources: {
                  name: 'Source',
                },
                boxSize: {
                  name: 'Box size',
                },
                reversalAmount: {
                  name: 'Reversal amount',
                },
                style: {
                  name: 'Style',
                },
                atrLength: {
                  name: 'ATR length',
                },
                percentageLTP: {
                  name: 'Percentage',
                },
                oneStepBackBuilding: {
                  name: 'One step back building',
                },
              },
              downColor: '#F23645',
              upColor: '#089981',
              upColorProjection: '#336854',
              downColorProjection: '#7f323f',
            },
            baselineStyle: {
              topLineWidth: 2,
              bottomLineWidth: 2,
              priceSource: 'close',
              transparency: 50,
              baseLevelPercentage: 50,
              baselineColor: '#868993',
              topFillColor1: 'rgba(8, 153, 129, 0.28)',
              topFillColor2: 'rgba(8, 153, 129, 0.05)',
              bottomFillColor1: 'rgba(242, 54, 69, 0.05)',
              bottomFillColor2: 'rgba(242, 54, 69, 0.28)',
              topLineColor: '#089981',
              bottomLineColor: '#F23645',
            },
            rangeStyle: {
              barStyle: 0,
              thinBars: true,
              inputs: {
                range: 1, phantomBars: false,
              },
              inputInfo: {
                range: {
                  name: 'Range',
                },
                phantomBars: {
                  name: 'Phantom bars',
                },
              },
              upColor: '#089981',
              downColor: '#F23645',
              upColorProjection: '#336854',
              downColorProjection: '#7f323f',
              candlesUpColor: '#089981',
              candlesDownColor: '#F23645',
              candlesBorderUpColor: '#089981',
              candlesBorderDownColor: '#F23645',
              candlesWickUpColor: '#089981',
              candlesWickDownColor: '#F23645',
            },
            volFootprintStyle: {
              drawWick: true,
              drawBorder: true,
              barColorsOnPrevClose: false,
              drawBody: true,
              deltaAdjust: true,
              showSummary: true,
              type: 'Buy and sell',
              pointOfControl: true,
              imbalanceHighlight: {
                visible: true, buyColor: '#089981', sellColor: '#F23645',
              },
              inputs: {
                rowSize: 'Auto',
                atrLength: 14,
                imbalancePercent: 300,
                ticksPerRow: 100,
                showVA: true,
                vaPercent: 70,
                calcStackedImbalance: false,
                stackedImbalanceCount: 3,
              },
              upColor: '#089981',
              downColor: '#F23645',
              borderColor: '#378658',
              borderUpColor: '#089981',
              borderDownColor: '#F23645',
              wickColor: '#737375',
              wickUpColor: '#089981',
              wickDownColor: '#F23645',
              bgColors: {
                adjBuyBgColors: ['#082621', '#004D40', '#06806B', '#22AB94'],
                adjSellBgColors: ['#331F20', '#991F29', '#CC2F3C', '#F7525F'],
                adjTotalBgColors: ['#142E61', '#143EB2', '#1E53E5', '#3179F5'],
                buyBgColor: '#004D40',
                sellBgColor: '#991F29',
                totalBgColor: '#143EB2',
                pocColor: '#D1D4DC',
              },
            },
            baseLineColor: '#5D606B',
            prevClosePriceLineColor: '#555555',
            priceLineColor: '',
            symbol,
            shortName,
            timeframe: '',
            interval,
            unitId: null,
            currencyId,
            priceAxisProperties: {
              autoScale: true,
              autoScaleDisabled: false,
              lockScale: false,
              percentage: false,
              percentageDisabled: false,
              log: false,
              logDisabled: false,
              alignLabels: true,
              isInverted: false,
              indexedTo100: false,
              showSymbolLabels: false,
              showStudyPlotLabels: true,
              m_priceRange: {
                m_maxValue: 1.14728, m_minValue: 1.14304,
              },
              m_isAutoScale: true,
              m_isPercentage: false,
              m_isIndexedTo100: false,
              m_isLog: false,
              m_isLockScale: false,
              m_isInverted: false,
              m_height: 562,
              m_topMargin: 0.05,
              m_bottomMargin: 0.05,
            },
          },
        }],
        mainSourceId: '_seriesId',
        stretchFactor: 2000,
        leftAxisesState: [],
        rightAxisesState: [{
          state: {
            id: 'wstQ0nV9oTRB',
            m_priceRange: null,
            m_isAutoScale: true,
            m_isPercentage: false,
            m_isIndexedTo100: false,
            m_isLog: false,
            m_isLockScale: false,
            m_isInverted: false,
            m_topMargin: 0.1,
            m_bottomMargin: 0.08,
            alignLabels: true,
            logFormula: {
              logicalOffset: 4, coordOffset: 0.0001,
            },
            hasCalculatedPriceRange: true,
          },
          sources: ['_seriesId', studyId],
        }],
        overlayPriceScales: {},
        priceScaleRatio: null,
        isCollapsed: false,
        isMaximized: false,
        mode: 0,
      }],
      timeScale: {
        m_barSpacing: 6, m_rightOffset: 10, rightOffsetPercentage: 5, usePercentageRightOffset: false,
      },
      chartProperties: {
        paneProperties: {
          backgroundType: 'gradient',
          gridLinesMode: 'both',
          vertGridProperties: {
            color: 'rgba(240, 243, 250, 0.06)',
          },
          horzGridProperties: {
            color: 'rgba(240, 243, 250, 0.06)',
          },
          crossHairProperties: {
            style: 2,
            transparency: 0,
            width: 1,
            color: '#9598A1',
            'color:': '#9598A1',
            labelBackgroundColor: '#131722',
          },
          topMargin: 10,
          bottomMargin: 8,
          axisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            indexedTo100: false,
            log: false,
            logDisabled: false,
            alignLabels: true,
            isInverted: false,
            showSymbolLabels: false,
            showStudyPlotLabels: true,
            m_priceRange: {
              m_maxValue: 1.14728, m_minValue: 1.14304,
            },
            m_isAutoScale: true,
            m_isPercentage: false,
            m_isIndexedTo100: false,
            m_isLog: false,
            m_isLockScale: false,
            m_isInverted: false,
            m_height: 562,
            m_topMargin: 0.05,
            m_bottomMargin: 0.05,
          },
          legendProperties: {
            showStudyArguments: false,
            showStudyTitles: true,
            showStudyValues: true,
            showSeriesTitle: true,
            showSeriesOHLC: true,
            showLegend: true,
            showLastDayChange: false,
            showBarChange: true,
            showVolume: false,
            showBackground: true,
            showPriceSource: true,
            backgroundTransparency: 50,
            showLogo: true,
            showTradingButtons: true,
            showTradingButtonsMobile: true,
            wrapText: false,
            showOnlyPriceSource: true,
          },
          separatorColor: '#2A2E39',
          background: '#131722',
          backgroundGradientStartColor: '#181C27',
          backgroundGradientEndColor: '#131722',
          gridProperties: {
            color: '#e1ecf2', style: 0,
          },
          leftAxisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            log: false,
            logDisabled: false,
            alignLabels: true,
            indexedTo100: false,
            isInverted: false,
            showSymbolLabels: false,
            showStudyPlotLabels: false,
          },
          rightAxisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            log: false,
            logDisabled: false,
            alignLabels: true,
            indexedTo100: false,
            isInverted: false,
            showSymbolLabels: false,
            showStudyPlotLabels: true,
            m_priceRange: {
              m_maxValue: 1.14728, m_minValue: 1.14304,
            },
            m_isAutoScale: true,
            m_isPercentage: false,
            m_isIndexedTo100: false,
            m_isLog: false,
            m_isLockScale: false,
            m_isInverted: false,
            m_height: 562,
            m_topMargin: 0.05,
            m_bottomMargin: 0.05,
          },
          overlayPropreties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            log: false,
            logDisabled: false,
            alignLabels: true,
            showSymbolLabels: false,
            showStudyPlotLabels: false,
          },
          rightOffset: null,
          unitedGridProperties: {
            color: 'rgba(240, 243, 250, 0)', style: 0,
          },
        },
        scalesProperties: {
          fontSize: 12,
          scaleSeriesOnly: false,
          showSeriesLastValue: true,
          seriesLastValueMode: 1,
          showSeriesPrevCloseValue: false,
          showStudyLastValue: false,
          showSymbolLabels: true,
          showStudyPlotLabels: false,
          showBidAskLabels: false,
          showPrePostMarketPriceLabel: true,
          showFundamentalNameLabel: false,
          showFundamentalLastValue: false,
          barSpacing: 6,
          axisHighlightColor: 'rgba(41, 98, 255, 0.25)',
          axisLineToolLabelBackgroundColorCommon: '#2962FF',
          axisLineToolLabelBackgroundColorActive: '#143EB2',
          showPriceScaleCrosshairLabel: true,
          showTimeScaleCrosshairLabel: true,
          crosshairLabelBgColorLight: '#0F0F0F',
          crosshairLabelBgColorDark: '#3D3D3D',
          saveLeftEdge: false,
          textColor: '#B2B5BE',
          lineColor: 'rgba(240, 243, 250, 0)',
          backgroundColor: '#ffffff',
          showLeftScale: false,
          showRightScale: true,
          showLastValue: false,
          showSeriesLastValueProperty: false,
          showStudyLastValueProperty: false,
          showSeriesPrevCloseValueDisabled: true,
        },
        publishedChartsTimelineProperties: {
          type: 'BarsMarksContainer', id: 'PublishedChartsTimeline', zorder: 10000003, pinnedTooltips: {},
        },
        chartEventsSourceProperties: {
          visible: false,
          futureOnly: true,
          breaks: {
            color: 'rgba(85, 85, 85, 1)', visible: false, style: 2, width: 1,
          },
          currencyFilter: '',
        },
        tradingProperties: {
          showPositions: true,
          positionPL: {
            visibility: true, display: 0,
          },
          bracketsPL: {
            visibility: true, display: 0,
          },
          showOrders: true,
          showExecutions: true,
          showExecutionsLabels: false,
          showReverse: true,
          horizontalAlignment: 2,
          extendLeft: true,
          lineLength: 5,
          lineWidth: 1,
          lineStyle: 1,
          showTPSL: true,
        },
        priceScaleSelectionStrategyName: 'auto',
      },
      sessions: {
        properties: {
          sessionHighlight: {
            backgrounds: {
              preMarket: {
                color: '#FF9800', transparency: 92, visible: true,
              },
              postMarket: {
                color: '#2962FF', transparency: 92, visible: true,
              },
              electronic: {
                color: '#2962FF', transparency: 92, visible: true,
              },
              outOfSession: {
                color: '#2962FF', transparency: 92, visible: true,
              },
            },
            vertlines: {
              sessBreaks: {
                color: '#4985e7', style: 2, visible: false, width: 1,
              },
            },
          },
        },
      },
      version: 3,
      timezone: 'Etc/UTC',
      shouldBeSavedEvenIfHidden: true,
      linkingGroup: null,
      chartId: '1',
    }],
    symbolLock: 0,
    intervalLock: 0,
    trackTimeLock: 0,
    dateRangeLock: 0,
    crosshairLock: 1,
    layoutsSizes: {
      s: [{
        percent: 1,
      }],
    },
  };
}

function createStudyMetaInfoMap(rawIndicator) {
  const indicatorScriptId = rawIndicator.metaInfo.id;
  const indicatorScriptVersion = rawIndicator.metaInfo.pine.version;
  const indicatorMetaInfoVersion = rawIndicator.metaInfo._metainfoVersion;
  return {
    [`${indicatorScriptId}[v.${indicatorScriptVersion}]`]: {
      _serverMetaInfoVersion: indicatorMetaInfoVersion,
      fullId: indicatorScriptId,
      shortId: indicatorScriptId.split('@')[0],
      packageId: 'tv-scripting',
      productId: 'tv-scripting',
      version: 101,
      palettes: {},
      graphics: {},
      ...rawIndicator.metaInfo,
    },
  };
}

function createStudyStrategy(studyId, rawIndicator) {
  const indicatorScriptId = rawIndicator.metaInfo.id;
  return {
    type: 'StudyStrategy',
    id: studyId,
    state: {
      inputs: {
        ...rawIndicator.inputValues, pineId: '', pineVersion: '',
      },
      styles: rawIndicator.metaInfo.defaults.styles || {},
      graphics: rawIndicator.metaInfo.defaults.graphics || {},
      filledAreasStyle: rawIndicator.metaInfo.defaults.filledAreasStyle || {},
      bands: rawIndicator.metaInfo.defaults.bands || {},
      ohlcPlots: rawIndicator.metaInfo.defaults.ohlcPlots || {},
      palettes: rawIndicator.metaInfo.defaults.palettes || {},
      filledAreas: rawIndicator.metaInfo.defaults.filledAreas || {},
      visible: true,
      showLegendValues: true,
      showLabelsOnPriceScale: true,
      precision: 'default',
      strategy: {
        orders: {
          showLabels: true, showQty: true, visible: true,
        },
      },
      parentSources: [],
    },
    zorder: -10000,
    ownFirstValue: null,
    metaInfo: `${indicatorScriptId}[v.${rawIndicator.metaInfo.pine.version}]`,
  };
}

module.exports = {
  createLayoutContentBlob(layoutName, currencyId, symbol, interval, studyId, rawIndicator) {
    const emptyBlob = createEmptyLayoutContentBlob(layoutName, currencyId, symbol, interval, studyId);
    if (!rawIndicator) return emptyBlob;

    const blob = { ...emptyBlob };
    blob.studyMetaInfoMap = createStudyMetaInfoMap(rawIndicator);

    const studyStrategy = createStudyStrategy(studyId, rawIndicator);
    blob.charts[0].panes[0].sources.push(studyStrategy);

    return blob;
  },

  getStudySourcesFromLayoutContent(layoutContent) {
    return layoutContent.charts.map((chart) => chart.panes.map((pane) => pane.sources.filter((source) => source.type === 'StudyStrategy')).flat()).flat();
  },

  getMainSeriesSourceFromLayoutContent(layoutContent) {
    const sources = layoutContent.charts.map((chart) => chart.panes.map((pane) => pane.sources.filter((source) => source.type === 'MainSeries')).flat()).flat();
    return sources[0];
  },
};
